## Creating Numpy Arrays

In [1]:
import numpy as np

#### 1. Creating an array from a regular Python list or tuple using the array function

In [2]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [4]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

#### 2. NumPy offers several functions to create arrays with initial placeholder content

create an array of zeros with desired shape(x,y)

    * x == number of rows
    * y == number of columns in array

In [6]:
array_of_zeroes = np.zeros((3,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
array_of_ones = np.ones((3,4))

In [8]:
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**np.empty() is not the same as np.zeros()**

One may get the same output. But np.empty() returns a new array of given shape and type, without initializing entries(the entries may be zero but not always)

Used when you plan to populate the array but need to create one quickly first. If you want an array of zeros, use np.zeros()

In [9]:
array_empty = np.empty((2,3))  
array_empty

array([[ 2.00000000e+000, -2.00389823e+000,  4.44659081e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

#### np.eye() creates an eyedentity matrix

In [12]:
array_eye = np.eye(4)

In [13]:
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 3. To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists

arange(start, stop, step, dtype)

In [14]:
array_of_evens = np.arange(2, 20, 2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### It also accepts float arguments

In [16]:
array_of_floats = np.arange( 0, 2, 0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

#### Two Dimensional Arrays

In [17]:
array_2d = np.array([(2,4,6),(3,5,7)]) 
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [18]:
array_2d.shape

(2, 3)

#### Using reshape to create n dimensional arrays

In [20]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [21]:
array_nd=np.arange(6).reshape(3,2)

In [22]:
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

###### The reshape will only take arguments that multiply to te number on arrange function. For example for arange(8), the possible combinations for reshape are (2,4),(4,2),(2,2,2)

In [30]:
array_nd = np.arange(6).reshape(2,3) 
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
array_nd = np.arange(8).reshape(2,2,2) 
array_nd

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

**ones_like**: Produce an array of all 1's with the given shape and dtype/ ones_like takes another array and producres a ones array of the same shape and dtype/ There's also a zeros_like and empty_like

In [33]:
array_ones = np.ones_like(array_nd)

In [34]:
array_ones

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [35]:
array_zeros = np.zeros_like(array_nd)

In [36]:
array_zeros

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [37]:
array_empty = np.empty_like(array_nd)


In [38]:
array_empty

array([[[4611686018427387904, 4611686018427387904],
        [                  8,                   0]],

       [[                  0,                   0],
        [                  0,                   0]]])

### Array creation functions:

 **Array**  --> Convert input data(list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicity specifying a dtype. Copies the input data by default

<b>asarray</b> : Convert input to ndarray, but do not copy if the input is already an ndarray

<b>arange</b> : Like the built-in range but returns an ndarray instead of a list.

<b>ones, ones_like</b> : Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.

<b>zeros, zeros_like</b> : Like ones and ones_like but producing arrays of 0’s instead

<b>empty, empty_like</b> : Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

<b>eye, identity</b> : Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)

In [41]:
array_identity = np.identity(4)

In [42]:
array_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])