In [5]:
import numpy as np

## Arithmetic Operations

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. We will see what broadcasting is in the upcoming lessons.

In [2]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [3]:
a + b

array([15, 15, 15])

In [4]:
a - b

array([5, 5, 5])

In [5]:
a * b

array([50, 50, 50])

In [6]:
a / b

array([2., 2., 2.])

In [7]:
a % 3  

array([1, 1, 1])

In [8]:
a < 35

array([ True,  True,  True])

In [9]:
a > 25

array([False, False, False])

In [10]:
a ** 2

array([100, 100, 100])

## dot function or method

In [12]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0], [3,4]] )

print('A:\n', A)
print('B:\n', B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


#### This gives element-wise multiplication

In [13]:
A * B

array([[2, 0],
       [0, 4]])

#### This gives the matrix multiplication

In [14]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [15]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

#### Matrix Multiplication - [row, col]= sum(all elements in row * all element in col)

A key distinction to make with arithmetic is the case of matrix multiplication using the dot product. 
NumPy gives every matrix a **dot()** method we can use to carry-out dot product operations with other matrices

 <img src="https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png" />

I have addd matrix dimensions at the bottom of this figure to stress that two matrices have to have the same dimension on the side they face each other with. You can visialize this operation as looking like this 

 <img src="https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-2.png" />

Matrix Multiplication - [row, col]= sum(all elements in row * all element in col)

In [21]:
data = np.arange(1,4)

In [22]:
data

array([1, 2, 3])

In [8]:
power_of_ten = np.power(np.arange(1,4),1000000)

In [9]:
power_of_ten

array([                  1,                   0, 7682401271709541633])

In [23]:
## navi way to do:
n = 1
for i in range(1,6): 
    if i==1 :
        print (i)
    n=10*n 
    print(n)

1
10
100
1000
10000
100000
