## Universal Functions

NumPy provides standard trigonometric function, function for arithmetic,handling complex numbers, statistical functions, etc. In NumPy, these are called "Universal function" (unfunc).

In [1]:
import numpy as np

In [2]:
angles = np.array([0,30,45,60,90])

In [6]:
angles_radians = angles * ((np.pi)/180)

In [4]:
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [8]:
print ('Sine of angles in the array')
print (np.sin(angles_radians))

Sine of angles in the array
[0.         0.5        0.70710678 0.8660254  1.        ]


In [9]:
angles_radians = np.radians(angles)
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [10]:
print('Cosine of angles in the array')
print(np.cos(angles_radians))

Cosine of angles in the array
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [15]:
sinA = np.sin(angles * np.pi/180)

In [16]:
print(sinA)

print('Compute sine inverse of angles. Returned values are in radians')

inv = np.arcsin(sinA)
print(inv)

[0.         0.5        0.70710678 0.8660254  1.        ]
Compute sine inverse of angles. Returned values are in radians
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [20]:
angles = np.array([0,30,45,60,90])

print(angles)

[ 0 30 45 60 90]


In [23]:
inv = np.arcsin(90)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


In [22]:
inv

0.0

### Statistial Functions

In [24]:
test_scores = np.array([32.32, 56.98, 21.52, 44.32, 
                        55.63, 13.75, 43.47, 43.34])

In [25]:
print('Mean test scores of the students: ')
print(np.mean(test_scores))

Mean test scores of the students: 
38.91625


In [26]:
print('Median test scores of the students: ')
print(np.median(test_scores))

Median test scores of the students: 
43.405


We will now perform basic statistical methods on real life dataset. We will use salary data of 1147 European developers.

In [29]:
pwd

'/Users/manishsinha/Documents/GitHub/pythonTutorial/Numpy/Demo/02/demos/Manish_ex'

In [32]:
salaries = np.genfromtxt('/Users/manishsinha/Documents/GitHub/pythonTutorial/Numpy/Demo/02/demos/data/salary.csv', 
                         delimiter=',')

In [33]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [35]:
salaries.shape

(1147,)

In [36]:
mean     = np.mean(salaries)
median   = np.median(salaries)
sd       = np.std(salaries)
variance = np.var(salaries)

In [40]:
print('Mean = %i' %mean)
print('Median = %i' %median)
print('Standard Deviation = %i' %sd)
print('Variance = %i' %variance)

Mean = 55894
Median = 48000
Standard Deviation = 55170
Variance = 3043770333


In [41]:
print('Mean = %f' %mean)
print('Median = %f' %median)
print('Standard Deviation = %f' %sd)
print('Variance = %f' %variance)

Mean = 55894.538797
Median = 48000.000000
Standard Deviation = 55170.375509
Variance = 3043770333.847448
