## Fancy Indexing - Integer Arrays

NumPy arrays can be indexed with slices, but also with boolean or integer arrays <b>(masks)</b>. It means passing an array of indices to access multiple array elements at once. This method is called fancy indexing. It creates copies not views.

In [1]:
import numpy as np
import csv

In [2]:
a = np.arange(12)**2

In [3]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

Suppose we want to access three different elements. We could do it like this:

In [4]:
a[2],a[6],a[8]

(4, 36, 64)

Alternatively, we can pass a single list or array of indices to obtain the same result:

In [5]:
indx_1 = [2,6,8]

In [6]:
indx_1

[2, 6, 8]

In [7]:
a[indx_1]

array([ 4, 36, 64])

When using fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed

In [8]:
food = np.array([["blueberry","strawberry","cherry","blackberry"],
                 ["pinenut","hazelnuts","cashewnut","coconut"],
                 ["mustard","paprika","nutmeg","clove"]])

In [9]:
food

array([['blueberry', 'strawberry', 'cherry', 'blackberry'],
       ['pinenut', 'hazelnuts', 'cashewnut', 'coconut'],
       ['mustard', 'paprika', 'nutmeg', 'clove']], dtype='<U10')

##### We will now select the corner elements of this array

In [11]:
row = np.array([[0,0],[2,2]])
col = np.array([[0,3],[0,3]])

In [12]:
food[row,col]

array([['blueberry', 'blackberry'],
       ['mustard', 'clove']], dtype='<U10')

otice that the first value in the result is food[0,0], next is food[0,3] , food[2,0] and lastly food[2,3]

### Modifying Values with Fancy Indexing

Just as fancy indexing can be used to access parts of an array, it can also be used to modify parts of an array.

In [13]:
food[row,col] = "000000"

In [14]:
food

array([['000000', 'strawberry', 'cherry', '000000'],
       ['pinenut', 'hazelnuts', 'cashewnut', 'coconut'],
       ['000000', 'paprika', 'nutmeg', '000000']], dtype='<U10')

we can use any assignment-type operator for this. Consider following example.

In [15]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [16]:
indx_1

[2, 6, 8]

In [17]:
a[indx_1]=999

In [18]:
a

array([  0,   1, 999,   9,  16,  25, 999,  49, 999,  81, 100, 121])

In [19]:
indx_1

[2, 6, 8]

In [20]:
a[indx_1]-=100

In [21]:
a

array([  0,   1, 899,   9,  16,  25, 899,  49, 899,  81, 100, 121])