In [1]:
import pandas as pd

In [3]:
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')

In [5]:
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [6]:
titanic_train.tail()

PassengerId  Survived  Pclass                               Name     Sex  \
151          152         1       1  Pears, Mrs. Thomas (Edith Wearne)  female   
152          153         0       3                   Meo, Mr. Alfonzo    male   
153          154         0       3    van Billiard, Mr. Austin Blyler    male   
154          155         0       3              Olsen, Mr. Ole Martin    male   
155          156         0       1        Williams, Mr. Charles Duane    male   

      Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
151  22.0      1      0      113776  66.6000    C2        S  
152  55.5      0      0  A.5. 11206   8.0500   NaN        S  
153  40.5      0      2    A/5. 851  14.5000   NaN        S  
154   NaN      0      0   Fa 265302   7.3125   NaN        S  
155  51.0      0      1    PC 17597  61.3792   NaN        C

In [7]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
titanic_train.dtypes =='object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [9]:
a = titanic_train.dtypes[titanic_train.dtypes == 'object']

In [10]:
a

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [11]:
a = titanic_train.dtypes[titanic_train.dtypes == 'object'].index

In [12]:
a

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [15]:
titanic_train[a]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female   
152                                   Meo, Mr. Alfonzo    male   
153                    van Billiard, Mr. Austin Blyler    male   
154                              Olsen, Mr. Ole Martin    male   
155                        Williams, Mr. Charles Duane    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
151            113776    C2        S  
152        A.5. 11206   NaN        S  
153          A/5. 851   NaN        S  
154         Fa 265302   NaN        S  
155          PC 17597   NaN        C  

[156 rows x 5 columns]

In [16]:
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [13]:
titanic_train[a].describe()

Name   Sex  Ticket        Cabin Embarked
count                       156   156     156           31      155
unique                      156     2     145           28        3
top     Emir, Mr. Farred Chehab  male  237736  C23 C25 C27        S
freq                          1   100       2            2      110

In [14]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [17]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [18]:
titanic_train[['Name','Sex','Age']]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0
152                                   Meo, Mr. Alfonzo    male  55.5
153                    van Billiard, Mr. Austin Blyler    male  40.5
154                              Olsen, Mr. Ole Martin    male   NaN
155                        Williams, Mr. Charles Duane    male  51.0

[156 rows x 3 columns]

In [21]:
sorted(titanic_train["Name"])

['Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Attalah, Miss. Malake',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Barton, Mr. David John',
 'Bateman, Rev. Robert James',
 'Baxter, Mr. Quigg Edmond',
 'Beesley, Mr. Lawrence',
 'Bing, Mr. Lee',
 'Bonnell, Miss. Elizabeth',
 'Boulos, Mrs. Joseph (Sultana)',
 'Braund, Mr. Owen Harris',
 'Burke, Mr. Jeremiah',
 'Byles, Rev. Thomas Roussel Davids',
 'Caldwell, Master. Alden Gates',
 'Cann, Mr. Ernest Charles',
 'Carrau, Mr. Francisco M',
 'Celotti, Mr. Francesco',
 'Chaffee, Mr. Herbert Fuller',
 'Christmann, Mr. Emil',
 'Chronopoulos, Mr. Apostolos',
 'Coelho, Mr. 

In [19]:
# Check the first 15 sorted names
sorted(titanic_train["Name"])[5:10:2]

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [22]:
titanic_train["Name"].describe()

count                         156
unique                        156
top       Emir, Mr. Farred Chehab
freq                            1
Name: Name, dtype: object

In [24]:
titanic_train[["Ticket"]]

Ticket
0           A/5 21171
1            PC 17599
2    STON/O2. 3101282
3              113803
4              373450
..                ...
151            113776
152        A.5. 11206
153          A/5. 851
154         Fa 265302
155          PC 17597

[156 rows x 1 columns]

In [23]:
titanic_train[["Ticket"]][4:9]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [25]:
titanic_train["Ticket"].describe()

count        156
unique       145
top       237736
freq           2
Name: Ticket, dtype: object

In [26]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [27]:
titanic_train["mani"]="manish"


In [28]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'mani'],
      dtype='object')

In [29]:
titanic_train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked    mani  
0      0         A/5 21171   7.2500   NaN        S  manish  
1      0          PC 17599  71.2833   C85        C  manish  
2      0  STON/O2. 3101282   7.9250   NaN        S  manish  
3      0            113803  53.1000  C123        S  manish  
4      0            373450   8.0500   NaN        S  manish  
5      0            330877   8.4583   NaN        Q  manish  
6      0             17463  51.8625   E46        S  manish  
7      1            349909  21.0750   NaN        S  manish  
8      2            347742  11.1333   NaN        S  manish  
9      0            237736  30.0708   NaN        C  manish

In [30]:
     # Check the first 15 tickets
titanic_train["Cabin"][0:15]  

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [36]:
titanic_train[['Name','Survived']]

Name  Survived
0                              Braund, Mr. Owen Harris         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                               Heikkinen, Miss. Laina         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)         1
4                             Allen, Mr. William Henry         0
..                                                 ...       ...
151                  Pears, Mrs. Thomas (Edith Wearne)         1
152                                   Meo, Mr. Alfonzo         0
153                    van Billiard, Mr. Austin Blyler         0
154                              Olsen, Mr. Ole Martin         0
155                        Williams, Mr. Charles Duane         0

[156 rows x 2 columns]

In [39]:
titanic_train[['Name','Survived','Pclass']]

Name  Survived  Pclass
0                              Braund, Mr. Owen Harris         0       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...         1       1
2                               Heikkinen, Miss. Laina         1       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)         1       1
4                             Allen, Mr. William Henry         0       3
..                                                 ...       ...     ...
151                  Pears, Mrs. Thomas (Edith Wearne)         1       1
152                                   Meo, Mr. Alfonzo         0       3
153                    van Billiard, Mr. Austin Blyler         0       3
154                              Olsen, Mr. Ole Martin         0       3
155                        Williams, Mr. Charles Duane         0       1

[156 rows x 3 columns]

In [37]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])


In [38]:
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [40]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [41]:
titanic_train["Pclass"].unique()   # Check unique cabins

array([3, 1, 2])

In [42]:
new_c_Cabin = pd.Categorical(titanic_train["Cabin"])


In [43]:
new_c_Cabin

[NaN, C85, NaN, C123, NaN, ..., C2, NaN, NaN, NaN, NaN]
Length: 156
Categories (28, object): [A5, A6, B28, B30, ..., F G73, F2, F33, G6]

In [44]:
import numpy as np

In [45]:
# convert data to str 
char_cabin = titanic_train["Cabin"].astype(str) 

In [48]:
type(char_cabin)

pandas.core.series.Series

In [49]:
# Take first letter
new_cabin = [cabin[0] for cabin in char_cabin]

In [50]:
new_cabin

['n',
 'C',
 'n',
 'C',
 'n',
 'n',
 'E',
 'n',
 'n',
 'n',
 'G',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'A',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'B',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'B',
 'C',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'E',
 'n',
 'n',
 'n',
 'A',
 'D',
 'n',
 'n',
 'n',
 'n',
 'D',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'E',
 'D',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'D',
 'C',
 'n',
 'B',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'n',
 'F',
 'n',
 'n',
 'C',
 'n',
 'n',
 'n',
 'n']

In [52]:
new_cabin = pd.Categorical(new_cabin)

In [53]:
new_cabin

[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [54]:
titanic_train["Cabin"] = new_cabin 

In [55]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked    mani  
0      0         A/5 21171   7.2500     n        S  manish  
1      0          PC 17599  71.2833     C        C  manish  
2      0  STON/O2. 3101282   7.9250     n        S  manish  
3      0            113803  53.1000     C        S  manish  
4      0            373450   8.0500     n        S  manish

In [56]:
titanic_train["Age"].isnull() 

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [57]:
missing = np.where(titanic_train["Age"].isnull() == True)

In [58]:
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154]),)

In [81]:
titanic_train["Age"].head(6)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
Name: Age, dtype: float64

In [83]:
max(titanic_train["Fare"])

263.0

In [84]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88]),)

In [98]:
titanic_train.iloc[[27,28]]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
28           29         1       3   O'Dwyer, Miss. Ellen "Nellie"  female   

     Age  SibSp  Parch  Ticket      Fare Cabin Embarked    mani  
27  19.0      3      2   19950  263.0000     C        S  manish  
28   NaN      0      0  330959    7.8792     n        Q  manish

In [85]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked    mani  
27  19.0      3      2  19950  263.0     C        S  manish  
88  23.0      3      2  19950  263.0     C        S  manish

In [99]:
len(missing[0])

30

In [100]:
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154]),)

In [103]:
titanic_train["Family"]=titanic_train["SibSp"] + titanic_train["Parch"]

In [105]:
titanic_train[["Family","SibSp","Parch"]].head()

Family  SibSp  Parch
0       1      1      0
1       1      1      0
2       0      0      0
3       1      1      0
4       0      0      0

In [106]:
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))


In [107]:
most_family

(array([59, 71]),)

In [108]:
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked    mani  Family  
59  11.0      5      2  CA 2144  46.9     n        S  manish       7  
71  16.0      5      2  CA 2144  46.9     n        S  manish       7

In [109]:
import numpy as np

In [110]:
import pandas as pd

In [111]:
labels = ['a','b','c']

In [112]:
my_data = [10,20,30]

In [113]:
arr = np.array(my_data)

In [114]:
arr

array([10, 20, 30])

In [115]:
d = {'a':10, 'b': 20, 'c':30}

In [116]:
d

{'a': 10, 'b': 20, 'c': 30}

In [117]:
print ("Labels:", labels)

Labels: ['a', 'b', 'c']


In [118]:
print("My Data:", my_data)

My Data: [10, 20, 30]


In [119]:
print("Dictionary:", d)

Dictionary: {'a': 10, 'b': 20, 'c': 30}


In [120]:
pd.Series(my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [121]:
My_Dictionary=pd.Series(my_data, index=labels)

In [122]:
My_Dictionary

a    10
b    20
c    30
dtype: int64

In [123]:
print ("\nHolding numerical data\n",'-'*25, sep='')



Holding numerical data
-------------------------


In [124]:
print ("\nHolding numerical data\n",'-'*25)


Holding numerical data
 -------------------------


In [125]:
print ("\nHolding text labels\n",'-'*20, sep='')
print(pd.Series(labels))


Holding text labels
--------------------
0    a
1    b
2    c
dtype: object


In [126]:
d = {'a':"kjhk",'b':20,'c':30}
d.items

<function dict.items>

In [127]:
pd.DataFrame(d,index = ['a','b','c'])

a   b   c
a  kjhk  20  30
b  kjhk  20  30
c  kjhk  20  30

In [128]:
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
print(pd.Series([type, sum, max]))


Holding objects from a dictionary
----------------------------------------
0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object


In [153]:
ser1 = pd.Series([1,2,3,4],index = [2,4,6,8])
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [136]:
ser2

CA    1
OR    2
NV    5
AZ    4
dtype: int64

In [149]:
ser1[0:3:2]


2    1
6    3
dtype: int64

In [161]:
ser1[4]

2

In [166]:
print ("\nIndexing by number (positional value in the series)\n",'-'*52, sep='')
print("Value for CA in ser1:", ser1[2])
print("Value for AZ in ser1:", ser1[8])
print("Value for NV in ser2:", ser2['NV'])
ser1


Indexing by number (positional value in the series)
----------------------------------------------------
Value for CA in ser1: 1
Value for AZ in ser1: 4
Value for NV in ser2: 5


2    1
4    2
6    3
8    4
dtype: int64