## Basic Array Operation 

In [1]:
import numpy as np

In [2]:
a = np.array([10,10,10])

In [3]:
b = np.array([5,5,5])

#### element of array should be same

In [4]:
#Addition:
a+b

array([15, 15, 15])

In [6]:
#substraction
a-b

array([5, 5, 5])

In [7]:
#Multiplication

In [8]:
a*b

array([50, 50, 50])

In [9]:
#Division
a/b

array([2., 2., 2.])

In [10]:
a%b

array([0, 0, 0])

In [11]:
a%3

array([1, 1, 1])

In [12]:
a<35

array([ True,  True,  True])

In [13]:
a>25

array([False, False, False])

In [15]:
aa=np.array([[1,1],[0,1]])

In [16]:
bb=np.array([[2,0],[3,4]])

In [17]:
print('A:\n',aa)

A:
 [[1 1]
 [0 1]]


In [18]:
print('B:\n',bb)

B:
 [[2 0]
 [3 4]]


In [19]:
aa*bb

array([[2, 0],
       [0, 4]])

### Dot Product

A key distinction to make with arithmetic is the case of matrix multiplication using the dot product. 
NumPy gives every matrix a **dot()** method we can use to carry-out dot product operations with other matrices

 <img src="https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png" />

I have addd matrix dimensions at the bottom of this figure to stress that two matrices have to have the same dimension on the side they face each other with. You can visialize this operation as looking like this 


 <img src="https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-2.png" />

Matrix Multiplication - [row, col]= sum(all elements in row * all element in col)

In [26]:
a=np.array([1,2,3])

In [31]:
a

array([1, 2, 3])

In [29]:
b=np.array([[1,10],[100,1000],[10000,100000]])

In [30]:
b

array([[     1,     10],
       [   100,   1000],
       [ 10000, 100000]])

In [32]:
a.dot(b)

array([ 30201, 302010])

### Matrix Aggregation

#### We can aggregate matrices the same way we aggregated vectors

 <img src="https://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png" />


In [96]:
a=np.array([[1,2],[3,4],[5,6]])

In [97]:
a.max()

6

In [98]:
a.min()

1

In [99]:
a.sum()

21

#### Not only can we aggregate all the values in a matrix, but we can also aggregate across the rows or columns by using the axis parameter

 <img src="https://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png" />


In [84]:
a.max(axis=0)

array([2, 4, 6])

In [85]:
a

array([[1, 3, 5],
       [2, 4, 6]])

In [100]:
a=np.array([[1,2],[5,3],[4,6]])

In [101]:
a

array([[1, 2],
       [5, 3],
       [4, 6]])

In [102]:
a.max(axis=0)

array([5, 6])

In [103]:
a.max(axis=1)

array([2, 5, 6])

In [105]:
a

array([[1, 2],
       [5, 3],
       [4, 6]])

In [106]:
b

array([[     1,     10],
       [   100,   1000],
       [ 10000, 100000]])

In [107]:
##################

In [108]:
A = np.array([[1,1],[0,1]])

In [109]:
B = np.array([[2,0],[3,4]])

In [110]:
print('A:\n',A)

A:
 [[1 1]
 [0 1]]


In [111]:
print("B:\n",B)

B:
 [[2 0]
 [3 4]]


In [112]:
A.dot(B) ## multiplication

array([[5, 4],
       [3, 4]])

In [113]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [114]:
a

array([[1, 2],
       [5, 3],
       [4, 6]])

In [115]:
b

array([[     1,     10],
       [   100,   1000],
       [ 10000, 100000]])

In [116]:
a *=3 # a =a*3

In [117]:
a

array([[ 3,  6],
       [15,  9],
       [12, 18]])

In [118]:
b +=4

In [119]:
b

array([[     5,     14],
       [   104,   1004],
       [ 10004, 100004]])

In [120]:
ages = np.array([12,15,18,20])

In [121]:
ages.sum()

65

In [122]:
ages.min()

12